'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "stencil-library/dist/components";
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from "stencil-library/my-component";
import { SkButton as SkButtonElement, defineCustomElement as defineSkButton } from "stencil-library/sk-button";

export type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents, JSX.MyComponent> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents, JSX.MyComponent>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyComponentEvents,
    defineCustomElement: defineMyComponent
});

export type SkButtonEvents = NonNullable<unknown>;

export const SkButton: StencilReactComponent<SkButtonElement, SkButtonEvents, JSX.SkButton> = /*@__PURE__*/ createComponent<SkButtonElement, SkButtonEvents, JSX.SkButton>({
    tagName: 'sk-button',
    elementClass: SkButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SkButtonEvents,
    defineCustomElement: defineSkButton
});
